### ISSUE TITLE
Change links to direct downloads

### ISSUE THREAD

**Issue by jtvandijk** [jtvandijk/SA-TIED#1]
Download links direct to the GitHub page, but these can be changed to direct downloads.

**Comment by UCLPG-MSC-SGDS** [comment]
Change the link (where it says 'blob' inside the link): https://github.com/jtvandijk/SA-TIED/blob/master/data/attributes/sa-internet-access.dta

To: https://github.com/jtvandijk/SA-TIED/raw/master/data/attributes/sa-internet-access.dta

**Comment by jtvandijk** [comment]
Done, although does not necessarily work for (small) `csv` files as they might be opened in the browser instead of being downloaded directly. Download links to (small) `csv` files still are directed to the GitHub page, but note added to the instructions on how to save these. This seems the preferable option over uploading a `zip` file.
